Add a startup probe, if a cluster supports it.
jenkinsci/helm-charts pull request #119
Opened 2020-11-02 14:56 UTC by wzur-r3

Taken from https://github.com/helm/charts/issues/22279

# What this PR does / why we need it

My Jenkins installation starts for a while, and without setting a high value of master.healthProbeLivenessInitialDelay it restarts a few times.

One way of helping to mitigate this issue is to add a [Startup Probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes) to the Jenkins deployment. Startup Probes were introduced in K8s v1.16 so it should have a version check

See https://github.com/helm/charts/issues/22279 for an initial comments in previous chart incarnation for another example.

# Special notes for your reviewer

# Checklist

- [x] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed

2020-11-02 16:57 UTC, torstenwalter requested changes

2020-11-02 16:57 UTC, torstenwalter commented on charts/jenkins/templates/jenkins-master-deployment.yaml
> +            initialDelaySeconds: {{ .Values.master.healthProbeStartupInitialDelay }}
I would be in favor of `startupProbe` yaml block into values.yaml and render it using tpl function.
This way we could get rid of countless properties to configure a single probe.

I would take it as action item to do the same thing for the other probes for the 3.0.0 release.

2020-11-02 17:17 UTC, wzur-r3 commented on charts/jenkins/Chart.yaml
> +version: 2.15.4
I don't quite follow. It has been changed.

2020-11-02 17:29 UTC, torstenwalter commented on charts/jenkins/Chart.yaml
> +version: 2.15.4
I meant changing it to 2.16.0 ;-)

> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards compatible manner, and
> PATCH version when you make backwards compatible bug fixes.

https://semver.org/

2020-11-02 19:20 UTC, wzur-r3 commented on charts/jenkins/Chart.yaml
> +version: 2.15.4
personally I would leave it to a person who creates an actual release

2020-11-02 19:22 UTC, torstenwalter commented on charts/jenkins/Chart.yaml
> +version: 2.15.4
Merging creates a release ;-)

2020-11-02 19:28 UTC, wzur-r3 commented on charts/jenkins/templates/jenkins-master-deployment.yaml
> +            initialDelaySeconds: {{ .Values.master.healthProbeStartupInitialDelay }}
I'm not verse enough to replace it with tpl function. I simply used what someone else suggested in the other repo in May

2020-11-02 19:30 UTC, wzur-r3 commented on charts/jenkins/Chart.yaml
> +version: 2.15.4
updated as requested

2020-11-02 19:59 UTC, wzur-r3 commented on charts/jenkins/templates/jenkins-master-deployment.yaml
> +            initialDelaySeconds: {{ .Values.master.healthProbeStartupInitialDelay }}
also `initialDelaySecods` has been removed for startupProbe

2020-11-03 07:57 UTC, wzur-r3 commented
I'm really sorry for these forced pushes - I keep forgetting about signing my commits...

2020-11-04 07:49 UTC, torstenwalter commented on charts/jenkins/templates/jenkins-master-deployment.yaml
> +            initialDelaySeconds: {{ .Values.master.healthProbeStartupInitialDelay }}
I created https://github.com/wzur-r3/helm-charts/pull/1 to demonstrate what I meant with using the `tpl` function.

2020-11-05 15:42 UTC, wzur-r3 commented on charts/jenkins/templates/jenkins-master-deployment.yaml
> +            initialDelaySeconds: {{ .Values.master.healthProbeStartupInitialDelay }}
many thanks for that - I've already merged it your PR into this PR

2020-11-05 18:08 UTC, torstenwalter approved these changes

2020-11-05 18:08 UTC, merged