fix: java_ops issue with quoted values
jenkinsci/helm-charts pull request #141
Opened 2020-11-17 14:35 UTC by jBouyoud

Fix issues with quoted values like : `-Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self';"`

Signed-off-by: Julien Bouyoud <jBouyoud@users.noreply.github.com>

# What this PR does / why we need it

# Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #

# Special notes for your reviewer

# Checklist

- [ ] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] CHANGELOG.md was updated

2020-11-17 17:12 UTC, torstenwalter commented
Can you add/adjust the unit tests to cater for the change?

2020-11-18 17:18 UTC, jBouyoud commented
I'll be glad to do that but all test suite is failing. 
I've the same issue on my Desktop even on main branch, I tried to rollback to main with the same error (https://github.com/jenkinsci/helm-charts/pull/141/checks?check_run_id=1419552818) 

Tests are failing with : 
```
                - asserts[0] `isKind` fail
                        Template:       jenkins/templates/jenkins-master-deployment.yaml
                        DocumentIndex:  0
                        Expected to be kind:
                                Deployment
                        Actual:
                                null
```
I'm not very familiar with theses tools, and I can't find any info to be able to debug that.
Can you help me ? Is there any pro-tip to understand why the document is `null` ?

2020-11-18 17:33 UTC, torstenwalter commented
I would try to run helm template with the values of the test case. Could be that there is an issue when rendering it.

2020-11-19 07:07 UTC, jBouyoud commented
I've already tried this. 

For both `main` and my branch : 
- `helm template . -s templates/jenkins-master-deployment.yaml ` ✅  (output differ on two branch , pretty normal)
- `helm template . -s templates/jenkins-master-deployment.yaml | kaf - --dry-run=client ` ✅ 
- `helm unittest -f tests/jenkins-master-deployment-test.yaml .  ` ❌  with the error mentioned in the previous comment.
- Comment all `it` except `default values` ; run `helm unittest -f tests/jenkins-master-deployment-test.yaml .  ` ❌   with the same error

Environment (my desktop or CI) seems to be not relevant since I'm on MacOS and CI is executed on *nix platform and have the same issue

2020-11-19 19:35 UTC, torstenwalter commented
@jBouyoud Looks like an error with the newest version of helm unittest. If #142 works then you can rebase your changed on top of it.

2020-11-20 06:50 UTC, torstenwalter commented
```
				-        value: -Dcasc.reload.token=$(POD_NAME)
				+        value: "-Dcasc.reload.token=$(POD_NAME) \n"
```

2020-11-20 07:50 UTC, jBouyoud commented
Tests ✅

2020-11-20 19:44 UTC, torstenwalter requested changes

2020-11-20 19:44 UTC, torstenwalter commented on charts/jenkins/CHANGELOG.md
> +
Should be updated to 2.18.1 to reflect the chart version and moved above 2.18.0

2020-11-21 07:51 UTC, torstenwalter approved these changes

2020-11-21 07:52 UTC, torstenwalter commented
@jBouyoud Thank you for this improvement!

2020-11-21 07:52 UTC, merged