Fix name of _JAVA_OPTIONS
jenkinsci/helm-charts pull request #599
Opened 2022-03-31 14:06 UTC by gbonnefille

The variable expected by jvm is prefixed by underscore.

### What this PR does / why we need it

### Which issue this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

- fixes #528

### Special notes for your reviewer

### Checklist

- [ ] [DCO](https://github.com/jenkinsci/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] CHANGELOG.md was updated

2022-03-31 14:10 UTC, gbonnefille commented
It is only a document change... not sure I have to bump the version for that.

2022-03-31 14:22 UTC, timja requested changes

2022-03-31 15:04 UTC, timja commented on charts/jenkins/README.md
> +    - name: _JAVA_OPTIONS
do not use that value, see https://stackoverflow.com/a/40736904/4951015

2022-04-01 13:52 UTC, gbonnefille commented on charts/jenkins/README.md
> +    - name: _JAVA_OPTIONS
OK

2022-06-04 02:35 UTC, charlesmelby commented
It would be great if this PR could be completed.
I just wasted a couple hours trying to figure out this issue myself.

2022-06-04 07:06 UTC, timja commented
Few free to submit a new PR

2022-06-04 17:14 UTC, torstenwalter commented
Can you fix the DCO check and maybe update the title of the PR?

2022-06-07 07:14 UTC, gbonnefille commented
> Can you fix the DCO check and maybe update the title of the PR?

I added signed-of on all my commits.

2022-06-07 10:27 UTC, timja commented
and resolve the conflicts please?

2022-06-07 10:58 UTC, gbonnefille commented
> and resolve the conflicts please?

Done, but please, merge it quicly: it is a HUGE effort for a so trivial fix.

2022-06-07 11:19 UTC, timja approved these changes

2022-06-07 11:20 UTC, merged