Update k8s version to test on
jenkinsci/helm-charts pull request #955
Opened 2023-11-26 22:05 UTC by NotMyFault

2023-11-26 22:06 UTC, NotMyFault commented on .github/workflows/lint-test.yaml
> -          version: v3.12.0
According to https://github.com/Azure/setup-helm?tab=readme-ov-file#example, the default version is the newest, which we want to use.

2023-11-27 08:14 UTC, torstenwalter requested changes

2023-11-27 08:14 UTC, torstenwalter commented on .github/workflows/lint-test.yaml
> +          - "kindest/node:v1.26.11"
The specified versions do not exist. See https://hub.docker.com/r/kindest/node/tags

These kind of changes are a bit tricky as CI might trick you. chart-testing (`ct`) only checks changed charts. As you don't update the chart version it skips most of the tests and the build seems to be green.

What I often did is creating a draft PR, which bumps the chart version on top of changes like this to verify that everything is OK. See https://github.com/jenkinsci/helm-charts/pull/957 as an example. Feel free to charry-pick the versions from there.

2023-11-27 16:11 UTC, NotMyFault commented on .github/workflows/lint-test.yaml
> -          version: v3.12.0
Good catch, the action claims to default to the latest version tho.

2024-01-25 00:09 UTC, closed without merging